name: Test

on:
  pull_request:
    branches: [ main ]

jobs:

  linters:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      -
        uses: actions/checkout@v2
      -
        name: dependencies
        run: |
          python -m pip install poetry
          poetry install
      -
        name: install hooks
        run: poetry run pre-commit install-hooks
      -
        name: flake8
        run: poetry run pre-commit run flake8 --all-files --show-diff-on-failure
      -
        name: pylint
        run: poetry run pre-commit run pylint --all-files --show-diff-on-failure
